title: Page
pages: true
options: 
  preview: true
  status: false
  template: true
  url: true
  delete: false
files: true
  sortable: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
